### ISSUE TITLE
Create PUEO Batch Job script

### ISSUE THREAD

**Issue by dylanwells37** [osu-particle-astrophysics/GENETIS_PUEO#12]

**Comment by Ryantdebolt** [comment]
1. It seems that arasim dir and exec are the same variable.
2. Functions done in the batch job are similar to what we will need to do but we will have to customize for icemce inputs/outputs.
3. Some commented functions are relics from a previous batch management system.
4. Antenna performance metric files: programs related to the fitness function (plotters for example), araout files (possibly put somewhere else), and other functions related to the fitness.

**Comment by dylanwells37** [comment]
Make icemc read in the correct fikes
