### ISSUE TITLE
Create a Part_D1_PUEO script

### ISSUE THREAD

**Issue by dylanwells37** [osu-particle-astrophysics/GENETIS_PUEO#2]
The script should 
1. Move every .dat file into a file IceMC can access while changing them into a format IceMC can read
2. Grab each file individually and inputs it into IceMC
3. Outputs .txt file and moves it to correct location

**Comment by Ryantdebolt** [comment]
1. Use the array version to submit jobs.
2. Debug mode: Gives a seed to arasim to help hunt down issues. Possibly wait to implement this. (see random seed setting in the setup file for icemc)
