### ISSUE TITLE
Create a Part_D2 PUEO script

### ISSUE THREAD

**Issue by dylanwells37** [osu-particle-astrophysics/GENETIS_PUEO#3]
This script should
1. Check that all jobs were completed with no errors
2. Resubmit any failed jobs

**Comment by Ryantdebolt** [comment]
1. Previous error catch is specific to arasim. The program checks job files and searches for common error phrases. If it finds them, it reruns the jobs. Successful jobs will be flagged. May not need to do immediately as we do not yet know common errors for icemc. Maybe use the flags earlier.

**Comment by dylanwells37** [comment]
fix the way this counts files for PUEO version
