### ISSUE TITLE
Error reading root files

### ISSUE THREAD

**Issue by Machtay** [osu-particle-astrophysics/GENETIS_PUEO#31]
We're having some trouble with reading the root files produced by PUEOsim. We want to read them to get the error on the effective volumes. Here is the error message we're getting:

input_line_34:1:10: fatal error: 'Geoid.h' file not found
#include "Geoid.h"
         ^~~~~~~~~
TClass::Init:0: RuntimeWarning: no dictionary for class nicemc::EventSummary is available
TClass::Init:0: RuntimeWarning: no dictionary for class nicemc::LoopInfo is available
TClass::Init:0: RuntimeWarning: no dictionary for class nicemc::LoopInfo::Step is available
TClass::Init:0: RuntimeWarning: no dictionary for class nicemc::Neutrino is available
TClass::Init:0: RuntimeWarning: no dictionary for class nicemc::Energy is available
TClass::Init:0: RuntimeWarning: no dictionary for class nicemc::Neutrino::Path is available
TClass::Init:0: RuntimeWarning: no dictionary for class Geoid::Position is available
TClass::Init:0: RuntimeWarning: no dictionary for class nicemc::Interaction is available
TClass::Init:0: RuntimeWarning: no dictionary for class nicemc::Shower is available
TClass::Init:0: RuntimeWarning: no dictionary for class nicemc::SignalSummary is available
TClass::Init:0: RuntimeWarning: no dictionary for class nicemc::Event is available
Traceback (most recent call last):
  File "rootAnalysis.py", line 288, in <module>
    EffectiveVolume2('black','Update')
  File "rootAnalysis.py", line 102, in EffectiveVolume2
    if(passTree.event.neutrino.flavor==1):
AttributeError: 'TTree' object has no attribute 'event'

**Comment by dylanwells37** [comment]
The new version of rootAnalysis.py ran without issues during test loop.
