### ISSUE TITLE
Every antenna overwrites all antenna images

### ISSUE THREAD

**Issue by dylanwells37** [osu-particle-astrophysics/GENETIS_PUEO#32]
When we run the loop, each antenna record its image in detector images 0-49, resulting in the antenna images at the end of the loop all resulting from one individual.

**Comment by dylanwells37** [comment]
I think the issue is caused by the call of MakeImage(i) instead of MakeImage(j), since i isn't defined where MakeImage is called. I changed this, and we will see if it works in Generation 16.

**Comment by Machtay** [comment]
Yep, this seems to have fixed it.
