### ISSUE TITLE
Create XFintoPUEO.py 

### ISSUE THREAD

**Issue by dylanwells37** [osu-particle-astrophysics/GENETIS_PUEO#4]
1. Start from a copy of XFintoARA.py
2. Modify the python program to change the XFdtd outputs into a format IceMC can read in.
3. Save these changes into the correct file type.

**Comment by Machtay** [comment]
This script has been written by Jacob and modified by me. The recent push contains the working version. 

There is a temporary fix in Part_C.sh for an issue where the cross polarization values seem to be too low, so we use the cross-pol values from the original PUEOsim data. I will open a new issue for that and, barring any opposition, consider this one closed.
